name: MKDocs Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'examples/**'
      - 'autosdk.docs.json'
      - '.github/workflows/mkdocs.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    uses: tryAGI/workflows/.github/workflows/mkdocs-pages.yml@main
    secrets: inherit
